name: tugas2
description: "A new Flutter project."
publish_to: "none" # Hapus baris ini jika kamu ingin menerbitkan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/jogging.png
  - assets/images/icon.jpg
  - assets/images/image1.jpg
  - assets/images/image2.jpg
  - assets/images/image3.jpg
  - assets/images/maguwo.jpg
  - assets/images/tambakboyo.jpg
  - assets/images/tamanugm.jpg
