// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCANmNCuWxPzVqR5VPdzF5dFQdxerQCLs0',
    appId: '1:90736298016:web:a6c63275d01ce98eab1445',
    messagingSenderId: '90736298016',
    projectId: 'nekostream-1945',
    authDomain: 'nekostream-1945.firebaseapp.com',
    databaseURL: 'https://nekostream-1945.firebaseio.com',
    storageBucket: 'nekostream-1945.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2mqEHZ7VvNM0DksK9pCkhklHJeEAiBwI',
    appId: '1:90736298016:android:0d5debc4ef670c53ab1445',
    messagingSenderId: '90736298016',
    projectId: 'nekostream-1945',
    databaseURL: 'https://nekostream-1945.firebaseio.com',
    storageBucket: 'nekostream-1945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZQHH_1a_B8hzzctpGO5v669ceHYjAaFw',
    appId: '1:90736298016:ios:de279037c3fb24b6ab1445',
    messagingSenderId: '90736298016',
    projectId: 'nekostream-1945',
    databaseURL: 'https://nekostream-1945.firebaseio.com',
    storageBucket: 'nekostream-1945.appspot.com',
    iosBundleId: 'com.example.tugas2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZQHH_1a_B8hzzctpGO5v669ceHYjAaFw',
    appId: '1:90736298016:ios:de279037c3fb24b6ab1445',
    messagingSenderId: '90736298016',
    projectId: 'nekostream-1945',
    databaseURL: 'https://nekostream-1945.firebaseio.com',
    storageBucket: 'nekostream-1945.appspot.com',
    iosBundleId: 'com.example.tugas2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCANmNCuWxPzVqR5VPdzF5dFQdxerQCLs0',
    appId: '1:90736298016:web:b792a5a348e7a8b4ab1445',
    messagingSenderId: '90736298016',
    projectId: 'nekostream-1945',
    authDomain: 'nekostream-1945.firebaseapp.com',
    databaseURL: 'https://nekostream-1945.firebaseio.com',
    storageBucket: 'nekostream-1945.appspot.com',
  );

}